//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Views.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of Views.DtoClasses.EmployeeView from the entity model.</summary>
	public static partial class EmployeeViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<EmployeeManagment.EntityClasses.EmployeeEntity, Views.DtoClasses.EmployeeView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<EmployeeManagment.EntityClasses.EmployeeEntity, Views.DtoClasses.EmployeeView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static EmployeeViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to Views.DtoClasses.EmployeeView which instances are projected from the 
		/// results of the specified baseQuery, which returns EmployeeManagment.EntityClasses.EmployeeEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Views.DtoClasses.EmployeeView instances</returns>
		public static IQueryable<Views.DtoClasses.EmployeeView> ProjectToEmployeeView(this IQueryable<EmployeeManagment.EntityClasses.EmployeeEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to Views.DtoClasses.EmployeeView which instances are projected from the
		/// EmployeeManagment.EntityClasses.EmployeeEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>EmployeeManagment.EntityClasses.EmployeeEntity instance created from the specified entity instance</returns>
		public static Views.DtoClasses.EmployeeView ProjectToEmployeeView(this EmployeeManagment.EntityClasses.EmployeeEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<EmployeeManagment.EntityClasses.EmployeeEntity, Views.DtoClasses.EmployeeView>> CreateProjectionFunc()
		{
			return p__0 => new Views.DtoClasses.EmployeeView()
			{
				DateOfBirth = p__0.DateOfBirth,
				Email = p__0.Email,
				FirstName = p__0.FirstName,
				Gender = p__0.Gender,
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				LastName = p__0.LastName,
				PhotoPath = p__0.PhotoPath,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_EmployeeView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

