//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EmployeeManagment.HelperClasses
{
	/// <summary>Field Creation Class for entity EmployeeEntity</summary>
	public partial class EmployeeFields
	{
		/// <summary>Creates a new EmployeeEntity.DateOfBirth field instance</summary>
		public static EntityField2 DateOfBirth { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.DateOfBirth); }}
		/// <summary>Creates a new EmployeeEntity.Email field instance</summary>
		public static EntityField2 Email { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Email); }}
		/// <summary>Creates a new EmployeeEntity.FirstName field instance</summary>
		public static EntityField2 FirstName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.FirstName); }}
		/// <summary>Creates a new EmployeeEntity.Gender field instance</summary>
		public static EntityField2 Gender { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Gender); }}
		/// <summary>Creates a new EmployeeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.Id); }}
		/// <summary>Creates a new EmployeeEntity.IsActive field instance</summary>
		public static EntityField2 IsActive { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.IsActive); }}
		/// <summary>Creates a new EmployeeEntity.LastName field instance</summary>
		public static EntityField2 LastName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.LastName); }}
		/// <summary>Creates a new EmployeeEntity.PhotoPath field instance</summary>
		public static EntityField2 PhotoPath { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(EmployeeFieldIndex.PhotoPath); }}
	}
	

}