//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using EmployeeManagment.FactoryClasses;
using EmployeeManagment.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EmployeeManagment.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitDepartmentEntityInfo();
			InitEmployeeEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits DepartmentEntity's info objects</summary>
		private void InitDepartmentEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DepartmentFieldIndex), "DepartmentEntity");
			this.AddElementFieldInfo("DepartmentEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)DepartmentFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("DepartmentEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)DepartmentFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("DepartmentEntity", "NameEnglish", typeof(System.String), false, false, false, false,  (int)DepartmentFieldIndex.NameEnglish, 250, 0, 0);
		}

		/// <summary>Inits EmployeeEntity's info objects</summary>
		private void InitEmployeeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(EmployeeFieldIndex), "EmployeeEntity");
			this.AddElementFieldInfo("EmployeeEntity", "DateOfBirth", typeof(System.DateTime), false, false, false, false,  (int)EmployeeFieldIndex.DateOfBirth, 0, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "DepartmentId", typeof(System.Int32), false, true, false, false,  (int)EmployeeFieldIndex.DepartmentId, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeEntity", "Email", typeof(System.String), false, false, false, true,  (int)EmployeeFieldIndex.Email, 250, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "FirstName", typeof(System.String), false, false, false, false,  (int)EmployeeFieldIndex.FirstName, 250, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "Gender", typeof(System.Int32), false, false, false, false,  (int)EmployeeFieldIndex.Gender, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)EmployeeFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("EmployeeEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)EmployeeFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "LastName", typeof(System.String), false, false, false, false,  (int)EmployeeFieldIndex.LastName, 250, 0, 0);
			this.AddElementFieldInfo("EmployeeEntity", "PhotoPath", typeof(System.String), false, false, false, false,  (int)EmployeeFieldIndex.PhotoPath, 250, 0, 0);
		}
	}
}