//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Employee'.</summary>
	[Serializable]
	[DataContract]
	public partial class EmployeeView
	{
		/// <summary>Gets or sets the DateOfBirth field. Derived from Entity Model Field 'Employee.DateOfBirth'</summary>
		[DataMember]
		public System.DateTime DateOfBirth { get; set; }
		/// <summary>Gets or sets the Department field. </summary>
		[DataMember]
		public EmployeeViewTypes.Department Department { get; set; }
		/// <summary>Gets or sets the DepartmentId field. Derived from Entity Model Field 'Employee.DepartmentId (FK)'</summary>
		[DataMember]
		public System.Int32 DepartmentId { get; set; }
		/// <summary>Gets or sets the Email field. Derived from Entity Model Field 'Employee.Email'</summary>
		[DataMember]
		public System.String Email { get; set; }
		/// <summary>Gets or sets the FirstName field. Derived from Entity Model Field 'Employee.FirstName'</summary>
		[DataMember]
		public System.String FirstName { get; set; }
		/// <summary>Gets or sets the Gender field. Derived from Entity Model Field 'Employee.Gender'</summary>
		[DataMember]
		public System.Int32 Gender { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Employee.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Employee.IsActive'</summary>
		[DataMember]
		public System.Boolean IsActive { get; set; }
		/// <summary>Gets or sets the LastName field. Derived from Entity Model Field 'Employee.LastName'</summary>
		[DataMember]
		public System.String LastName { get; set; }
		/// <summary>Gets or sets the PhotoPath field. Derived from Entity Model Field 'Employee.PhotoPath'</summary>
		[DataMember]
		public System.String PhotoPath { get; set; }
	}

	namespace EmployeeViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'Department (Department)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Department
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Department.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'Department.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the NameEnglish field. Derived from Entity Model Field 'Department.NameEnglish'</summary>
			[DataMember]
			public System.String NameEnglish { get; set; }
		}
	}

}




